id: P000379
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:36:56.048253
source_metadata:
  id: bdr:W1KG23599
  title: བཀའ་བློན་རྟོགས་བརྗོད།
  author: ''
  volumes:
    dda22eb70a6b43818478e07f0ebf4779:
      image_group_id: I1KG23677
      title: Volume 1 of bka' blon rtogs brjod/
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
